### ISSUE TITLE
package on pypi

### ISSUE THREAD

**Issue by raylu** [scottchiefbaker/dool#50]
##### SUMMARY
make dool installable via `pip install dool`

##### ISSUE TYPE
 - Feature Idea

see also: #4

---

the structure of the code is a bit... inconducive to python packaging. `dool` isn't importable, so it's hard to set it up as a console script. I made a symlink `dool.py` → `dool`, but the structure is still pretty odd. it relies on some globals to be set, so after moving the `__main__` block into a `_main()` function, I added some `global`s. I don't really understand what the `else` block is for (how can `__name__` ever not be `__main__`?) so I deleted it

```diff
diff --git c/dool i/dool
index 8c645b7..7910aa4 100755
--- c/dool
+++ i/dool
@@ -51,6 +53,24 @@ pluginpath = [
     '/usr/local/share/dool/',
 ]
 
+def _main():
+    global op, theme
+    try:
+        initterm()
+        op = Options(os.getenv('DOOL_OPTS','').split() + sys.argv[1:])
+        theme = set_theme()
+        if op.profile:
+            import profile
+            if os.path.exists(op.profile):
+                os.remove(op.profile)
+            profile.run('main()', op.profile)
+        else:
+            main()
+    except KeyboardInterrupt as e:
+        if op.update:
+            sys.stdout.write('\n')
+    exit(0)
+
 class Options:
     def __init__(self, args):
         self.args         = args
@@ -2825,23 +2845,6 @@ def kd(obj):
 
 ### Main entrance
 if __name__ == '__main__':
-    try:
-        initterm()
-        op = Options(os.getenv('DOOL_OPTS','').split() + sys.argv[1:])
-        theme = set_theme()
-        if op.profile:
-            import profile
-            if os.path.exists(op.profile):
-                os.remove(op.profile)
-            profile.run('main()', op.profile)
-        else:
-            main()
-    except KeyboardInterrupt as e:
-        if op.update:
-            sys.stdout.write('\n')
-    exit(0)
-else:
-    op = Options('')
-    step = 1
+    _main()
 
 # vim: tabstop=4 shiftwidth=4 expandtab autoindent softtabstop=4
```

with a few other minor tweaks and the `pyproject.toml` below, `flit install` works

```toml
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dool"
authors = [{name = "Scott Baker", email = "scott@perturb.org"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/scottchiefbaker/dool"

[project.scripts]
dool = "dool:_main"

[tool.flit.sdist]
exclude = [".github/*", ".gitignore", "docs/*", "examples/*", "install.py", "packaging/*", "Makefile"]
```

the main problem, though, is `plugins/`. it can't find any after installing

I doubt we want the package to be importable after installation as `plugins`, so we probably want to instead have a `src/` or `dool/` with a `__main__.py` and make `plugins/` a subdir of that. that'd require a minor change to `pluginpath` and updating the rpm and snap packaging code
